services:
  db:
    image: mysql:latest
    container_name: teddy-db
    env_file:
      - .env
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "mysql -h ${MYSQL_HOST} -u root -p$$MYSQL_ROOT_PASSWORD" ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - teddynet

networks:
  teddynet: