services:
  

  db:
    image: mysql:latest
    container_name: teddy-db
    env_file:
      - .env
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "mysql -h ${MYSQL_HOST} -u root -p$$MYSQL_ROOT_PASSWORD" ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - teddynet

  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
    # ports necessary for jaeger agents to run
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411


networks:
  teddynet: