services:
  api:
    image: mateusmlo/teddy-dev:latest
    environment:
      - MYSQL_HOST=db
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "${APP_PORT}:${APP_PORT}"
      - "8081:8081"
    networks:
      - teddynet

  db:
    image: mysql:latest
    container_name: teddy-db
    env_file:
      - .env
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "mysql -h ${MYSQL_HOST} -u root -p$$MYSQL_ROOT_PASSWORD" ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - teddynet

networks:
  teddynet: